using System;
using System.Numerics; // For BigInteger
using System.Text;
using System.Linq; // For Reverse
using KnightOnline.Infrastructure.Shared.Utils; // For HexDump.HexStringToByteArray (if needed) or similar

namespace KnightOnline.Infrastructure.Security
{
    public class Cryptor
    {
        // Hex: "1207500120128966" (from Java)
        // Decimal: 8675088083000000000
        private static readonly BigInteger PrivateKey = BigInteger.Parse("01207500120128966", System.Globalization.NumberStyles.HexNumber);

        private readonly BigInteger _tKey;
        private readonly byte[] _pKeyBytes; // Store the derived pKey bytes

        public Cryptor(BigInteger publicKeyFromClient) // This is the key generated by CryptorKey and sent by server
        {
            _tKey = publicKeyFromClient ^ PrivateKey;

            // Logic from Java: new StringBuilder(ArrayUtils.hexToString(tKey.toString(16))).reverse().toString().toCharArray();
            // 1. tKey.toString(16) -> Convert BigInteger tKey to hex string.
            // 2. ArrayUtils.hexToString(...) -> Convert this hex string to actual bytes (then to chars in Java).
            // 3. reverse() -> Reverse these bytes/chars.

            string tKeyHexString = _tKey.ToString("x"); // .NET BigInteger.ToString("x") is lowercase hex

            // ArrayUtils.hexToString in Java takes a hex string and converts pairs of hex chars to bytes, then to a string of those chars.
            // Example: "414243" -> new char[] { (char)0x41, (char)0x42, (char)0x43 } -> "ABC"
            // We need the byte array from the hex string.
            byte[] tKeyHexBytes = HexStringToByteArrayForCryptor(tKeyHexString);

            _pKeyBytes = tKeyHexBytes.Reverse().ToArray(); // Reverse the bytes
        }

        // Helper to mimic Java's ArrayUtils.hexToString's relevant part for pKey generation
        // It converts a hex string like "414243" to byte array {0x41, 0x42, 0x43}
        private static byte[] HexStringToByteArrayForCryptor(string hex)
        {
            if (hex.Length % 2 != 0)
            {
                // Pad with leading zero if odd length, as Java's BigInteger.toString(16) might not pad.
                hex = "0" + hex;
            }
            return Convert.FromHexString(hex); // .NET 5+
        }

        // EncryptionFast is symmetric, so it's also DecryptionFast
        public byte[] Process(byte[] data)
        {
            if (data == null) throw new ArgumentNullException(nameof(data));
            int length = data.Length;
            byte[] result = new byte[length];

            int lKey = (length * 157) & 0xFF;
            int rKey = 2157; // Initial rKey

            for (int i = 0; i < length; i++)
            {
                int rsk = (rKey >> 8) & 0xFF;
                // In Java, pKey was char[], direct cast to int. Here, _pKeyBytes is byte[].
                result[i] = (byte)(((data[i] ^ rsk) ^ _pKeyBytes[i % _pKeyBytes.Length]) ^ lKey);
                rKey = (rKey * 2171); // Keep rKey as a 32-bit int, matching Java's behavior.
                                      // Java int is 32-bit, so rKey * 2171 would not overflow as quickly, but rsk only uses one byte.
                                      // Let's ensure rKey stays within a range that produces similar rsk patterns.
                                      // The original Java code did not mask rKey after multiplication.
                                      // C# int is also 32-bit, so behavior should be similar.
            }
            return result;
        }
    }
}
