using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using KnightOnline.Domain.Players;
using KnightOnline.Domain.Accounts; // For UserId

namespace KnightOnline.Infrastructure.Data.Configurations
{
    public class PlayerConfiguration : IEntityTypeConfiguration<Player>
    {
        public void Configure(EntityTypeBuilder<Player> builder)
        {
            builder.HasKey(p => p.Id);

            builder.Property(p => p.Id)
                   .HasConversion(charId => charId.Value,
                                  dbValue => CharacterId.FromInt(dbValue))
                   .ValueGeneratedOnAdd(); // Assuming character IDs are generated by DB

            builder.Property(p => p.Name)
                   .IsRequired()
                   .HasMaxLength(100);
            builder.HasIndex(p => p.Name).IsUnique();

            // Configure foreign key for AccountId (Value Object)
            // EF Core can often map simple Value Objects used as FKs if their underlying type is a primitive
            // that EF Core understands (like Guid for UserId.Value).
            // Explicit configuration might be needed for more complex VOs or if issues arise.
            builder.Property(p => p.AccountId)
                   .HasConversion(accountId => accountId.Value,
                                  dbValue => UserId.FromGuid(dbValue))
                   .IsRequired();
            
            // If you had a navigation property to Account, you'd configure it here.
            // builder.HasOne<Account>() // Assuming Account entity exists
            //        .WithMany() // Assuming Account can have multiple players (characters)
            //        .HasForeignKey(p => p.AccountId);
        }
    }
}
